In [1]:
import numpy as np

In [2]:
docs = ["It was the best of times", "It was the worst of times", "It was the age of wisdom", "It was the age of foolishness"]

### 직접 구현

In [3]:
# 단어 사전 생성
word_dict = []

for sentences in docs:
    word_list = sentences.split()
    
    for word in word_list:
        if word not in word_dict:
            word_dict.append(word)

word_dict

['It',
 'was',
 'the',
 'best',
 'of',
 'times',
 'worst',
 'age',
 'wisdom',
 'foolishness']

In [4]:
sentences_vector = []

for sentences in docs:
    word_count = {key: 0 for key in word_dict}
    
    for i in word_dict:
        word_count[i] = sentences.count(i)

    sentences_vector.append(list(word_count.values()))

In [5]:
sentences_vector

[[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
 [1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
 [1, 1, 1, 0, 1, 0, 0, 1, 1, 0],
 [1, 1, 1, 0, 1, 0, 0, 1, 0, 1]]

### CountVectorizer() 사용

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
count_vectorizer = CountVectorizer()

In [8]:
count_vectorizer.fit(docs)

CountVectorizer()

In [9]:
bow = count_vectorizer.transform(docs)

In [10]:
print(bow.toarray())

[[0 1 0 1 1 1 1 1 0 0]
 [0 0 0 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 0 1 1 0]
 [1 0 1 1 1 1 0 1 0 0]]


In [11]:
# (문장, 단어 수)
print(bow.shape)

(4, 10)
